import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/commonents/Navbar";
import Footer from "@/commonents/Footer";
import { Toaster } from "react-hot-toast";
import { ContextProvider } from "@/context/Contaxt";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Prescripto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // const pathname = usePathname();
  // console.log(pathname);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased container-fluid m-auto relative mx-2`}
        cz-shortcut-listen="true"
      >
        <ContextProvider>
          <Navbar />
          <Toaster position="top-center" reverseOrder={false} />
          {children}
          <Footer />
        </ContextProvider>
      </body>
    </html>
  );
}
